export const CAMBODIA_PROVINCES = [
  'Banteay Meanchey',
  'Battambang',
  'Kampong Cham',
  'Kampong Chhnang',
  'Kampong Speu',
  'Kampong Thom',
  'Kampot',
  'Kandal',
  'Kep',
  'Koh Kong',
  'Kratie',
  'Mondulkiri',
  'Oddar Meanchey',
  'Pailin',
  'Phnom Penh',
  'Preah Sihanouk',
  'Preah Vihear',
  'Prey Veng',
  'Pursat',
  'Ratanakiri',
  'Siem Reap',
  'Stung Treng',
  'Svay Rieng',
  'Takeo',
  'Tbong Khmum',
];

export const CAMBODIA_CITIES = [
  'Phnom Penh',
  'Krong Battambang',
  'Krong Siem Reap',
  'Serei Saophoan',
  'Samraong',
  'Krong Kampong Cham',
  'Krong Kampong Chhnang',
  'Chbar Mon',
  'Stung Sen',
  'Krong Kampot',
  'Ta Khmau',
  'Krong Kep',
  'Khemarak Phoumin',
  'Krong Kratie',
  'Sen Monorom',
  'Pailin',
  'Sihanoukville',
  'Krong Preah Vihear',
  'Krong Prey Veng',
  'Pursat',
  'Banlung',
  'Stung Treng',
  'Svay Rieng',
  'Doun Kaev',
  'Suong',
];

export const CAMBODIA_PROVINCE_OPTIONS = CAMBODIA_PROVINCES.map((province) => ({
  value: province,
  label: province,
}));

